insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Quail - Jumbo Boneless', 9);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Jam - Apricot', 14);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Daikon Radish', 12);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pastry - Mini French Pastries', 2);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Soup - Boston Clam Chowder', 1);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Towel Multifold', 8);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Rum - Light, Captain Morgan', 10);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Macaroons - Homestyle Two Bit', 12);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Water - Tonic', 12);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Persimmons', 7);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Milk - 2% 250 Ml', 15);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Steamers White', 7);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Poppy Seed', 10);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Orange, 341 Ml', 3);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Vinegar - White', 13);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Squash - Acorn', 11);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Coffee - Decaffeinato Coffee', 12);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lid Coffeecup 12oz D9542b', 2);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Soy Protein', 8);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beans - Kidney, Red Dry', 15);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cafe Royale', 13);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Water - Mineral, Natural', 9);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cake Slab', 9);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ham - Cooked', 4);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese Cloth', 13);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Table Cloth 62x114 Colour', 5);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Taylors Reserve', 13);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Ej Gallo Sonoma', 10);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lamb - Whole, Frozen', 12);
insert into products (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pineapple - Golden', 12);
